// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8O1pR_KhReL8INX9pJJpYl2ndcpBQAfw',
    appId: '1:553304393821:web:af8942681630e763d5e5b4',
    messagingSenderId: '553304393821',
    projectId: 'hydroflow-e8b81',
    authDomain: 'hydroflow-e8b81.firebaseapp.com',
    storageBucket: 'hydroflow-e8b81.firebasestorage.app',
    measurementId: 'G-SKTKDBKWK2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvxPW2_jWZM2TKNDkFBb6w0jvSAuUdNJI',
    appId: '1:553304393821:android:82b9a78f112dad3ed5e5b4',
    messagingSenderId: '553304393821',
    projectId: 'hydroflow-e8b81',
    storageBucket: 'hydroflow-e8b81.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCoj6FC5eRBRu0FaWBQMnVPwTXx2dyKWk8',
    appId: '1:553304393821:ios:c73533ad4bb83f73d5e5b4',
    messagingSenderId: '553304393821',
    projectId: 'hydroflow-e8b81',
    storageBucket: 'hydroflow-e8b81.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCoj6FC5eRBRu0FaWBQMnVPwTXx2dyKWk8',
    appId: '1:553304393821:ios:c73533ad4bb83f73d5e5b4',
    messagingSenderId: '553304393821',
    projectId: 'hydroflow-e8b81',
    storageBucket: 'hydroflow-e8b81.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD8O1pR_KhReL8INX9pJJpYl2ndcpBQAfw',
    appId: '1:553304393821:web:6955a55fbe497cfcd5e5b4',
    messagingSenderId: '553304393821',
    projectId: 'hydroflow-e8b81',
    authDomain: 'hydroflow-e8b81.firebaseapp.com',
    storageBucket: 'hydroflow-e8b81.firebasestorage.app',
    measurementId: 'G-F5YC1S54F1',
  );

}