import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';
import 'login_page.dart'; // Import your LoginPage
import 'firebase_options.dart'; // Generated by FlutterFire CLI
import 'config/env_config.dart'; // Environment configuration
import 'theme/app_theme.dart'; // Import our new theme system

class ThemeController {
  static final ValueNotifier<ThemeMode> mode = ValueNotifier(ThemeMode.light);
  static void toggle() {
    mode.value =
        mode.value == ThemeMode.light ? ThemeMode.dark : ThemeMode.light;
  }

  static void set(ThemeMode m) {
    mode.value = m;
  }
}

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // Load environment variables
  await EnvConfig.load();

  // Initialize Firebase
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);

  // Debug: Print environment configuration
  EnvConfig.debugPrint();

  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return ValueListenableBuilder<ThemeMode>(
      valueListenable: ThemeController.mode,
      builder: (context, themeMode, _) {
        return MaterialApp(
          title: 'Hydraulic Assistant',
          debugShowCheckedModeBanner: false,
          theme: AppTheme.lightTheme,
          darkTheme: AppTheme.darkTheme,
          themeMode: themeMode,
          home: const LoginPage(),
        );
      },
    );
  }
}
