import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';
import 'login_page.dart'; // Import your LoginPage
import 'firebase_options.dart'; // Generated by FlutterFire CLI

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Login Demo',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        // primarySwatch: Colors.red,
        // scaffoldBackgroundColor: const Color(0xFFFF9E9E),
      ),
      home: const LoginPage(), // 👈 Start at LoginPage
    );
  }
}
// lib/upsert_pdf_page.dart
// import 'package:flutter/material.dart';
// import 'temp.dart';

// void main() {
//   runApp(const MyApp());
// }

// class MyApp extends StatelessWidget {
//   const MyApp({super.key});

//   @override
//   Widget build(BuildContext context) {
//     return MaterialApp(
//       title: 'PDF Upsert Demo',
//       debugShowCheckedModeBanner: false,
//       home: const UpsertPdfPage(),
//     );
//   }
// }
